export const groupProjectInfo = {
  farming: {
    title: "FARMING MATTERS",
    picTypes: [".mp4", ".mp4", ".mp4", ".mp4", ".mp4", ".mp4"],
    descriptionTitles: [
      "Software Engineering Capstone Project",
      "Study Question #1: Deterministic Data",
      "Study Question #1: Probabilistic Data",
      "Study Question #1: Consultant",
      "Study Question #2: Risk vs Reward",
      "Study Question #2: Insurance",
    ],
    description: [
      "With McMaster Professor Dr.Yiannokoulias as our group's client and supervisor, we created a web browser game with a farming theme whose purpose is to mask a psychological study.",
      "The psychological study investigates whether people prefer deterministic or probabilistic data. An example of this would be whether people prefer if their doctor says they are 75% confident in their diagnosis, or if they say their diagnosis is correct, but are wrong 25% of the time for both cases.",
      "This study question is analyzed through the game mechanic of the consultant. Every player is assigned deterministic of probabilistic data upon registration. The player can pay the consultant to receive this information.",
      "The consultant can provide information about the future turns pertaining to the weather or selling price of fully grown crops.",
      "The psychological study also investigates how people weigh risk vs reward, along with how their perception of this changes in response to the type of data they receive. This study question is analyzed through the game mechanic of insurance.",
      "The player can pay a small premium to insure a base selling price for their planted crops. If the consultant predicts bad weather or falling sale prices, will the study participant purchase insurance? And at what premium are they wiling to pay to ensure some base selling price?",
    ],
    tech: "Javascript (React), Three.Js, Express.Js, Node.Js, HTML, CSS, SQLite3",
    link: "https://github.com/brandonduong/Farming-Matters",
    year: "2022 - 2023",
  },
  clickerchat: {
    title: "CLICKER CHAT",
    descriptionTitles: [
      'Final Project for "Software Project Management"',
      "Enter any Chatroom",
      "Infinite Chat History",
      "Collaborative Clicker Minigame",
      "Complete Formal Documentation",
    ],
    description: [
      "Users are required to either login into an existing account, or register their own.",
      "Every user can join every chatroom.",
      "Each chatroom has their own chat history, of which is never deleted, acting as a time capsule!",
      "Each chatroom also has their own chat clicker, of which is never reset.",
      "Ranging from the problem statement all the way to the test report, all can be found in the repo.",
    ],
    tech: "Python (Django), HTML, CSS, SQLite3",
    link: "https://gitlab.cas.mcmaster.ca/kallaym/3xa3project",
    year: "2021",
  },
  deltahacksvii: {
    title: "PRESSURE DESTRESSER",
    descriptionTitles: [
      "DeltahacksVII",
      "Supports Patients and Doctors",
      "Record Daily Blood Pressure",
      "Doctor's Job Made Easier",
    ],
    description: [
      "Users can locate doctors in their area, or simply register their own account.",
      "Patients simply identify their location and doctor name, while doctors provide their location and license.",
      "Patients input and record their daily blood pressure with ease!",
      "Doctors can view all their patients recorded data, as well as send overall suggestions.",
    ],
    tech: "Javascript, HTML, CSS, Firebase",
    link: "https://github.com/EngandDeveloper/deltahacks6",
    year: "2021",
  },
  complain: {
    title: "COMPLAIN",

    descriptionTitles: [
      "DeltahacksVI",
      "Upload Complaints or Upload Fixes",
      "Litter Example",
      "Complete Complaint Map",
    ],
    description: [
      "A webapp where users can vent about their everyday life and surroundings, and view other locals' reportings.",
      "Users first upload a picture and description of their complaint. Then others can update what has been done about it.",
      "Looks like a user is complaining about litter in their area! In the future, someone can update on the litter situation.",
      "Using Bing's mapping API, all complaints are displayed on the map for all to see.",
    ],
    tech: "Javascript, HTML, CSS, Firebase",
    link: "https://github.com/EngandDeveloper/deltahacks6",
    year: "2020",
  },
};
