export const groupProjectInfo = {
  clickerchat: {
    title: "CLICKER CHAT",
    descriptionTitles: [
      'Final Project for "Software Project Management"',
      "Enter any Chatroom",
      "Infinite Chat History",
      "Collaborative Clicker Minigame",
      "Complete Formal Documentation",
    ],
    description: [
      "Users are required to either login into an existing account, or register their own.",
      "Every user can join every chatroom.",
      "Each chatroom has their own chat history, of which is never deleted, acting as a time capsule!",
      "Each chatroom also has their own chat clicker, of which is never reset.",
      "Ranging from the problem statement all the way to the test report, all can be found in the repo.",
    ],
    tech: "Python (Django), HTML, CSS, SQLite3",
    link: "https://gitlab.cas.mcmaster.ca/kallaym/3xa3project",
    year: "2021",
  },
  deltahacksvii: {
    title: "PRESSURE DESTRESSER",
    subtitle: "DELTAHACKS VII",
    descriptionTitles: [
      "DeltahacksVII",
      "Supports Patients and Doctors",
      "Record Daily Blood Pressure",
      "Doctor's Job Made Easier",
    ],
    description: [
      "Users can locate doctors in their area, or simply register their own account.",
      "Patients simply identify their location and doctor name, while doctors provide their location and license.",
      "Patients input and record their daily blood pressure with ease!",
      "Doctors can view all their patients recorded data, as well as send overall suggestions.",
    ],
    tech: "Javascript, HTML, CSS, Firebase",
    link: "https://github.com/EngandDeveloper/deltahacks6",
    year: "2021",
  },
  complain: {
    title: "COMPLAIN",
    subtitle: "DELTAHACKS VI",
    descriptionTitles: [
      "DeltahacksVI",
      "Upload Complaints or Upload Fixes",
      "Litter Example",
      "Complete Complaint Map",
    ],
    description: [
      "A webapp where users can vent about their everyday life and surroundings, and view other locals' reportings.",
      "Users first upload a picture and description of their complaint. Then others can update what has been done about it.",
      "Looks like a user is complaining about litter in their area! In the future, someone can update on the litter situation.",
      "Using Bing's mapping API, all complaints are displayed on the map for all to see.",
    ],
    tech: "Javascript, HTML, CSS, Firebase",
    link: "https://github.com/EngandDeveloper/deltahacks6",
    year: "2020",
  },
};
