export const personalProjectInfo = {
  recursion: {
    title: "BRANDONDUONG.VERCEL.APP",
    descriptionTitles: ["Fully Responsive and Beautifully Themed Portfolio"],
    description: [
      "My updated portfolio website that shows off me and my proud works nicely to hopefully land me a nice job so that I can support the people that are close to me!",
    ],
    tech: "Javascript (React - Next.js), HTML, CSS",
    link: "https://github.com/brandonduong/brandonduong-portfolio",
    year: "2023",
  },
  lolguess: {
    title: "LOLGUESS",
    descriptionTitles: [
      "Practice Tool for Popular Game Teamfight Tactics",
      "Play: Choose Region",
      "Play: Choose Rank",
      "Play: Guess Placements",
      "Play: Receive Feedback",
      "Track Progress and Learnings",
      "Compete on the Leaderboard",
      "Supporters Page",
    ],
    description: [
      "By using this tool, competitive and casual players can train and test their overall game knowledge to improve their ingame play.",
      "Users first choose a set of regions (NA, KR, JP, EU, etc.) to receive a random match from.",
      "Users then choose a set of ranks (Iron, Silver, Gold, Masters, Grandmasters, Challengers, etc.) to receive a random match from.",
      "Users then receive said random match from the possible regions and ranks. Given each player's end-game team composition, users must guess their placings from first to eighth and the overall match rank.",
      "After submitting their answer, users receive a score and feedback correspoing to how well they guessed the placings and rank within the game lobby.",
      "A user's guesses are stored and can be viewed on their profile, along with their all-time stats and graphs.",
      "Every day at 8pm EST the leaderboard updates, sortable by total score, correct placements, correct ranks, average score, or average correct placements.",
      "Anybody willing to generously support the practice tool is given their own section on the supporters page!",
    ],
    tech: "Typescript (Vue3), Node.Js, HTML, CSS, AWS (Amplify, AppSync, API Gateway, Lambda, Cognito, Route 53)",
    link: "https://github.com/brandonduong/LoLGuess",
    year: "2023",
  },
  prettypets: {
    title: "PRETTY PETS",
    picTypes: [".png", ".png", ".mp4", ".png", ".mp4"],
    descriptionTitles: [
      "Web Browser Gacha Game",
      "Adoption Centre: Adoption",
      "Adoption Centre: Abandonment",
      "Pet Groomer",
      "Job Board",
    ],
    description: [
      "Inspired by today's popular gacha games, collect a family of pretty pets to dominate the fasion show industry!",
      "Adopt pretty pets that have randomized species, base color, color filter, variant, traits, star level, and stats.",
      "Heartlessly betray and abandon your pets that don't meet up to your fasion standards to instead gain dye and stardust!",
      "Use unethically gained dye and stardust to reroll another pet's base color, color filter, variant, or increase their star rating!",
      "Assign your best pets to complete jobs in exchange for PrettyPoints. Use PrettyPoints to adopt more pets in hopes of collecting all species and variants with perfect stats and color!",
    ],
    tech: "Typescript (React), Node.Js, HTML, CSS, AWS (Amplify, AppSync, Lambda, Cognito)",
    link: "https://github.com/brandonduong/PrettyPets-v0",
    year: "2022",
  },
  lolpast: {
    title: "LOLPAST",
    descriptionTitles: [
      "Tool to Reminsce",
      "Matches Found Easy",
      "Overall Match Details",
      "Calculate Your Party's Winrate",
    ],
    description: [
      "Webapp that allows League of Legends players to cherrypick matches they've played with their friends, allowing searches for matches that contain up to 10 specified players.",
      "All match ids that contained the specified players are returned, where the user can then request more details with a click of a button.",
      "For each match, users can see the champions played, which team won, KDA, cs, damage, role, gold, date played, game mode, and game length.",
      "Find out your group's all-time success by filtering the winrate by either overall or specific game mode.",
    ],
    tech: "Javascript (Vue3), Node.Js, HTML, CSS, AWS (API Gateway, Lambda)",
    link: "https://github.com/brandonduong/lolpast",
    year: "2021",
  },
  slimestack: {
    title: "SLIMESTACK",
    descriptionTitles: [
      "Multiplayer Online Mobile Game",
      "Reach the top of the Leaderboard",
      "Create or Join Game Rooms",
      "1v1v1 Gameplay",
      "Turn-based Strategy",
    ],
    description: [
      "Compete against your friends in this strategy and puzzle-based game to get rich with slime coins!",
      "Be ready to play with easy to understand instructions and then show off your mastery.",
      "Either create a room and set its slime coin buy-in fee, or join an existing one using its Join Code!",
      "Invite 2 friends and wager all your slime coins.",
      "Take turns placing alike slimes on top of each other! Whoever can place the most slimes down wins.",
    ],
    tech: "Javascript (React Native), CSS, Firebase",
    link: "https://github.com/brandonduong/slimestack",
    year: "2021",
  },
  mygamelist: {
    title: "MYGAMELIST",
    descriptionTitles: [
      "A Game Focused 'MyAnimeList'",
      "Vast Library of Video Games",
      "Organize Games According to Your Needs",
      "Display Your Opinion to the World",
    ],
    description: [
      "Akin to the popular website 'MyAnimeList' that focuses on anime, users are able to rate and record their video game experiences!",
      "With a database powered by IGDB and Twitch.tv, never have trouble finding even your most niche video games.",
      "Users can easily create, view, and delete their nostalgia-driven lists in their profile page, of which can be shared via url!",
      "Individual Game Lists can also be shared via url for others to see!",
    ],
    tech: "Javascript (React), Express.Js, Node.Js, HTML, CSS, MongoDB",
    link: "https://github.com/brandonduong/mygamelist",
    year: "2021",
  },
  jinsight: {
    title: "JINSIGHT",
    descriptionTitles: [
      "Webapp Focusing on Reducing Waste",
      "Example Food-tracking List",
      "Editing Food-tracking Lists",
    ],
    description: [
      "Users that are logged into their own account can create and view food-tracking lists.",
      "Tracks all information necessary to minimize the amount of food that is wasted.",
      "Users can input their item information quickly and easily, as well as delete their lists.",
    ],
    tech: "Python (Django), HTML, CSS, MySQL",
    link: "https://github.com/brandonduong/Jinsight",
    year: "2020",
  },
  jgdiff: {
    title: "JGDIFF",
    descriptionTitles: [
      "Webapp Focusing on Analyzing LoL Data",
      "Example Calculation",
      "Multi-purpose",
    ],
    description: [
      "Users can maximize their chances of victory in the popular video game, League of Legends (LoL).",
      "Calculates data pertaining to early-game matchups.",
      "Can be used to enhance game knowledge, or test it.",
    ],
    tech: "Python (Django), HTML, CSS, MySQL",
    link: "https://github.com/brandonduong/JgDiff",
    year: "2020",
  },
  reaction: {
    title: "REACTION",
    picTypes: [".png", ".png", ".mp4", ".mp4", ".mp4"],
    descriptionTitles: [
      "Unique Take on Traditional 2D Platformers",
      "Level Selection",
      "Platforming with Gun Recoil",
      "Satisfying Obstacles to Overcome",
      "Puzzles",
    ],
    description: [
      "Requires players to cleverly utilize their various guns and their different recoils in order to progress.",
      "Includes 25 mind-bending levels!",
      "Unique platforming with the use of a pistol and deagle.",
      "Tight jumps and refreshing game mechanics provide a high skill ceiling.",
      "Clever puzzles that push the established mechanics to their limit.",
    ],
    tech: "C#",
    link: "https://github.com/brandonduong/reaction",
    year: "2020",
  },
  rose: {
    title: "THE ROSE",
    picTypes: [".png", ".png", ".mp4"],
    descriptionTitles: [
      "Character Mod for Slay the Spire",
      "All New Class Cards",
      "Passivity",
    ],
    description: [
      "Adds an entirely new character named Rose that is based off a penguin. Because penguins are cute.",
      "Over 60 new cards that introduce new mechanics and synergies to be used when playing as Rose!",
      "Unique mechanic that allows for a full pacifist run! Stack enough passivity on an enemy and they will happily flee!",
    ],
    tech: "Java",
    link: "https://github.com/brandonduong/The-Rose",
    year: "2020",
  },
  brandonduong: {
    title: "BRANDONDUONG.GITHUB.IO",
    descriptionTitles: ["Old Portfolio Website"],
    description: [
      "Fully responsive and built from scratch with heavy emphasis on utilizing Bootstrap! But... was visually weak, and so in contrast with this new portfolio website, you can really see how far I've come!",
    ],
    tech: "Javascript, HTML, CSS",
    link: "https://github.com/brandonduong/brandonduong.github.io",
    year: "2020",
  },
};
